apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rds-testing
  description: |
    THISIS TO TEST IF COMPONENT PERSISTS
  links:
    - title: Website
      url: http://backstage.io
spec:
  type: service
  owner: team-a
  lifecycle: experimental

  
